### ISSUE TITLE
Content.Search() results incomplete

### ISSUE THREAD

**Issue by timbrammer910** [ctreminiom/go-atlassian#113]
**go-atlassian version**
v1.4.2

**go-atlassian component**
- [ ] Jira Software Cloud
- [ ] Jira Agile Cloud
- [ ] Jira Service Management Cloud 
- [x] Confluence Cloud
- [ ] Atlassian Admin Cloud

**Describe the bug** :bug:
Content.Search() does not return fields beyond the title of the content.

**To Reproduce** :construction: 
Copy example code - https://docs.go-atlassian.io/confluence-cloud/content#search-contents-by-cql
Update host, username, password values

**Expected behavior** :white_check_mark: 
Return pages with values in models.ContentScheme

**Actual behavior**:
`Meeting notes <nil> <nil> <nil> <nil> <nil> [] <nil> <nil> <nil> []}`

**Additional context**
Using Content.Get with an ID works fine.

**Code snippet**
```go
package main

import (
	"context"
	"github.com/ctreminiom/go-atlassian/confluence"
	"log"
	"net/http"
	"os"
)

func main()  {

	var (
		host  = os.Getenv("HOST")
		mail  = os.Getenv("MAIL")
		token = os.Getenv("TOKEN")
	)

	instance, err := confluence.New(nil, host)
	if err != nil {
		log.Fatal(err)
	}

	instance.Auth.SetBasicAuth(mail, token)
	instance.Auth.SetUserAgent("curl/7.54.0")

	var (
		cql = "type=page"
		cqlContext = ""
		expand = []string{"childTypes.all", "metadata.labels"}
		maxResults = 50
	)

	contentPage, response, err := instance.Content.Search(context.Background(), cql, cqlContext, expand, "", maxResults)
	if err != nil {

		if response.Code == http.StatusBadRequest {
			log.Println(response.API)
		}
		log.Fatal(err)
	}

	log.Println("Endpoint:", response.Endpoint)
	log.Println("Status Code:", response.Code)
	log.Println(contentPage.Links.Next)


	for _, content := range contentPage.Results {
		log.Printf("%v", content)
	}
}

```

**Comment by ctreminiom** [comment]
Hi @timbrammer910 

It was a bug 🐞 but the PR https://github.com/ctreminiom/go-atlassian/pull/103 fixed the Content.Search() method. 

**FYI:** I just released the version [v1.4.3](https://github.com/ctreminiom/go-atlassian/releases/tag/v1.4.3)
