### ISSUE TITLE
IssueTypeScreenSchemeService: add `description` field when creating issue type screen schemes

### ISSUE THREAD

**Issue by iacabezasbaculima** [ctreminiom/go-atlassian#131]
**Is your feature request related to a problem? Please describe.**
The [`issueTypeScreenSchemeService`](https://github.com/ctreminiom/go-atlassian/blob/main/jira/v3/issueTypeScreenScheme.go)'s CREATE method does not currently support creating an issue type screen scheme with a description.

The method's payload model [IssueTypeScreenSchemePayloadScheme](https://github.com/ctreminiom/go-atlassian/blob/0e44336731ecd75ceed2f6a062d53fecd733335b/pkg/infra/models/jira_issue_type_screen_scheme.go#L20) is missing a `description` field.

**Describe the solution you'd like**
Add a `description` field to model [IssueTypeScreenSchemePayloadScheme](https://github.com/ctreminiom/go-atlassian/blob/0e44336731ecd75ceed2f6a062d53fecd733335b/pkg/infra/models/jira_issue_type_screen_scheme.go#L20) .

For example:
```go
type IssueTypeScreenSchemePayloadScheme struct {
	Name              string                                       `json:"name,omitempty"`
        Description       string                                       `json:"description,omitempty"` 
	IssueTypeMappings []*IssueTypeScreenSchemeMappingPayloadScheme `json:"issueTypeMappings,omitempty"`
}
```

API Reference: [Jira Cloud Platform v3 - Issue Type Screen Schemes](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-type-screen-schemes/#api-rest-api-3-issuetypescreenscheme-post)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ctreminiom** [comment]
Hi @iacabezasbaculima, thank you for taking the time to create the issue, I've added the Description tag on the PR https://github.com/ctreminiom/go-atlassian/pull/132 try to run _go get_ to the **main** branch

**Comment by iacabezasbaculima** [comment]
@ctreminiom It seems that you added the `description` field in a different struct.

I was referring to the following [struct](https://github.com/ctreminiom/go-atlassian/blob/92ae28189028b4347235ae6c6dfd8a1bedf8ceb9/pkg/infra/models/jira_issue_type_screen_scheme.go#L20):
```go
type IssueTypeScreenSchemePayloadScheme struct {
	Name              string                                       `json:"name,omitempty"`
---> add 'description' field here <---
	IssueTypeMappings []*IssueTypeScreenSchemeMappingPayloadScheme `json:"issueTypeMappings,omitempty"`
}
```

The struct above is used to create an issue type screen scheme by calling [this API endpoint](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-type-screen-schemes/#api-rest-api-3-issuetypescreenscheme-post) which supports passing a `description`.

Also, I think you may need to roll back this PR because the [IssueTypeScreenSchemeMappingPayloadScheme](https://github.com/ctreminiom/go-atlassian/blob/92ae28189028b4347235ae6c6dfd8a1bedf8ceb9/pkg/infra/models/jira_issue_type_screen_scheme.go#L25) used to specify [issueTypeMappings](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-type-screen-schemes/#api-rest-api-3-issuetypescreenscheme-post) does not support a `description` field passed in the [Jira API endpoint payload schema](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-type-screen-schemes/#api-rest-api-3-issuetypescreenscheme-post).

**Comment by ctreminiom** [comment]
Hi @iacabezasbaculima thank you for your feedback, I just merged a PR with the correct changes!

**Comment by iacabezasbaculima** [comment]
Hi @ctreminiom thank you for adding the correct changes :)
