### ISSUE TITLE
Add endpoints to manage Jira statuses

### ISSUE THREAD

**Issue by iacabezasbaculima** [ctreminiom/go-atlassian#140]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add full CRUD endpoints to manage Jira statuses.

Docs: https://support.atlassian.com/jira-cloud-administration/docs/what-are-issue-statuses-priorities-and-resolutions/#Issue-statuses
API Reference: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-status/#api-group-status

**Describe alternatives you've considered**
Currently, the library does not provide support for creating/reading/updating/deleting Jira statuses.

**Additional context**

**Comment by ctreminiom** [comment]
Hi @iacabezasbaculima, the implementation is now completed, here's the docs: https://docs.go-atlassian.io/jira-software-cloud/workflow/status#search-workflow-statuses

**Comment by iacabezasbaculima** [comment]
Hi @ctreminiom, thank you for implementing this feature! 👍
