### ISSUE TITLE
Enable `/wiki/rest/api/analytics/` endpoints

### ISSUE THREAD

**Issue by ctreminiom** [ctreminiom/go-atlassian#155]
**Is your feature request related to a problem? Please describe.**
Right now, the library doesn't support the ability to manipulate the Confluence page analytics

**Describe the solution you'd like**
Please implement the AnalyticsService on the Confluence module.

**Describe the tasks needed**

- Create an interface called AnalyticsConnector
- Under the interface, create two methods (Get, Gets) with their corresponding documentation (comments).
- Create a file called _backlog_impl_ under the _confluence/internal_ folder.
- Create the dedicated go structs under the _pkg/infra/models_ folder.
- Create a new implementation of the interface (please use the other service as a reference).
- Create the unit test cases with a minimum of 80% of coverage.

![image](https://user-images.githubusercontent.com/16035390/194789740-779ede9c-34d4-4fc9-95ad-d208a4cf4df7.png)
**Additional context**

- [https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-analytics/#api-wiki-rest-api-analytics-content-contentid-views-get](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-analytics/#api-wiki-rest-api-analytics-content-contentid-views-get)

**Comment by Swathi-L** [comment]
Hi @ctreminiom Can I work on this?

**Comment by ctreminiom** [comment]
Hi @Swathi-L, 

Sure!! It will be a pleasure
