### ISSUE TITLE
Add Atlassian Jira Assets

### ISSUE THREAD

**Issue by Fank** [ctreminiom/go-atlassian#202]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
I would like to have [Jira-native asset and configuration management](https://www.atlassian.com/software/jira/service-management/features/asset-and-configuration-management) support in this package.

**Describe alternatives you've considered**
I implemented multiple different solutions in the past to be able to communicate with assets:
- https://gitlab.com/mclgmbh/golang-pkg/jira-insight
- https://github.com/andygrunwald/go-jira/pull/565

**Additional context**
Assets in Jira was called "Insights" in the past, [blog post](https://community.atlassian.com/t5/Jira-Service-Management-articles/Coming-Soon-Insight-Changing-to-Assets/ba-p/2068056).

**Comment by Fank** [comment]
I can create a PR for it as well, if that is ok?
I would implement it based on https://github.com/ctreminiom/go-atlassian/tree/main/jira/sm, looks lightweight as well.

Forgot to mention the API docs can be found here: https://developer.atlassian.com/cloud/assets/rest/api-group-aql/

**Comment by ctreminiom** [comment]
Hi @Fank, thank you for the interest on this project!

- It seems the **assets** feature is related to Jira Service Management so I think it should be under the _SM_ package, what do you think?
- For the implementation, we can create the sub-services under the Object structure. Something like `sm.Object.Schema.Get()` `sm.Object.Type.Attribute.Delete()`
![image](https://github.com/ctreminiom/go-atlassian/assets/16035390/5833b405-d817-412f-8242-9ea8f0effb90)

- I can create a new branch and create the implementation together if you want.

**Comment by Fank** [comment]
> * It seems the **assets** feature is related to Jira Service Management so I think it should be under the _SM_ package, what do you think?

I don't think they are at the moment related, the only relation they share now is "asset" in the name.
I only work with Jira Software and Jira Assets, not Service Management. So i may miss knowledge about what the difference of SM and Assets is, not for now i would not merge those.

In Assets a "workspace id" is required, here were my thoughts about how to handle it: https://github.com/andygrunwald/go-jira/issues/495#issuecomment-1248575625

I would like to have your feedback about how you would to handle it.

> * For the implementation, we can create the sub-services under the Object structure. Something like `sm.Object.Schema.Get()` `sm.Object.Type.Attribute.Delete()`

I think the idea, might be good, i preferred using `assets.Objecttype.GetAttributes()` and `assets.Objecttypeattributes.Delete()`
So the "keywords" are the same found in the documentation.

So Objectype -> Objectype, and not Object.type
Why?

e.g. Objecttype has attributes but Objecttypeattribute are the attributes used in objectype.
So it would be object.type.GetAttributes()? and object.type,attribute.Create()?
For me it looks confusing.

**Comment by ctreminiom** [comment]
> I don't think they are related at the moment, the only relation they share now is "asset" in the name.  
I only work with Jira Software and Jira Assets, not Service Management. So i may miss knowledge about what the difference of SM and Assets is, not for now i would not merge those.

It's because Assets is a ITSM feature available on the Premium subscription.
![image](https://github.com/ctreminiom/go-atlassian/assets/16035390/b6419492-7953-4e3d-baaf-3032f508e822)

But after checking, assets is available on the Software and Business projects after enabling it so I would assume the feature scope is global. Having said that, I would think the best approach is create a dedicated module for assets, due it uses the workspace id as reference, not issues. 

> In Assets a "workspace id" is required, here were my thoughts about how to handle it:  [andygrunwald/go-jira#495 (comment)](https://github.com/andygrunwald/go-jira/issues/495#issuecomment-1248575625)

I agree with Andy's response about the first solution, this library is highly inspired on [go-jira](https://github.com/andygrunwald/go-jira) and the _service_ implementation are very similar to his.

> I think the idea, might be good, i preferred using assets.Objecttype.GetAttributes() and assets.Objecttypeattributes.Delete()
So the "keywords" are the same found in the documentation.

You're right.

> So Objectype -> Objectype, and not Object.type Why?

I was assuming the Assets endpoints were using the pattern workspace/$workspace_id/object/type/attribute/$attribute_Id, but it's not.

I'll be forward and create the module interfaces on a new branch 👍🏽

**Comment by Fank** [comment]
@ctreminiom could you give me write access so i could help you contributing in https://github.com/ctreminiom/go-atlassian/pull/204 .
While implementing it i could test it in our environment, since we are using assets.
We are currently using our own fork https://github.com/mcl-de/go-jira which i badly want to replace.

**Comment by ctreminiom** [comment]
@Fank you should be able to contribute on https://github.com/ctreminiom/go-atlassian/pull/204

**Comment by Fank** [comment]
Yes @ctreminiom i have seen it, i am working atm on replacing the go-jira with go-atlassian in our code.
So that i can start testing assets.

**Comment by Fank** [comment]
I just noticed from your comment here https://github.com/ctreminiom/go-atlassian/discussions/209 in assets are custom fields types available for jira:

`POST /rest/api/3/field`
```
{
  "id": "customfield_10191",
  "key": "customfield_10191",
  "name": "SLA Group",
  "untranslatedName": "SLA Group",
  "custom": true,
  "orderable": true,
  "navigable": true,
  "searchable": true,
  "clauseNames": [
    "cf[10191]",
    "SLA Group"
  ],
  "schema": {
    "type": "array",
    "items": "cmdb-object-field",
    "custom": "com.atlassian.jira.plugins.cmdb:cmdb-object-cftype",
    "customId": 10191
  }
}
```
![image](https://github.com/ctreminiom/go-atlassian/assets/1900106/0ae10e3f-a601-4226-bab3-a395f9db489a)

**Comment by ctreminiom** [comment]
@Fank try to pull the latest commit on https://github.com/ctreminiom/go-atlassian/pull/204

I added the support for the Asset custom-field extraction

```golang
assets, err := models.ParseAssetCustomField(response.Bytes, "customfield_10072")
if err != nil {
log.Fatal(err)
}

for _, asset := range assets {
fmt.Println(asset.Id, asset.WorkspaceId, asset.ObjectId)
}
```
