### ISSUE TITLE
Add issue array custom field access

### ISSUE THREAD

**Issue by Fank** [ctreminiom/go-atlassian#215]
**Is your feature request related to a problem? Please describe.**
When i am trying to filter for specific issues (using `v3.Issue.Search.Post()`) and then want to extract the custom fields from the search i need to custom unmarshal each field. 

**Describe the solution you'd like**
It would be nice to have to have something like `models.ParseFloatCustomField()` for arrays, in this case to parse the  `v3.Issue.Search.Post()` raw response output.

**Describe alternatives you've considered**
Copy paste the content of `models.ParseFloatCustomField()` and other functions to read the custom field values.

**Additional context**
-

**Comment by ctreminiom** [comment]
Hey @Fank, please refer to the docs: https://docs.go-atlassian.io/cookbooks/extract-customfields-from-issue-s
