### ISSUE TITLE
Adding attachment fails to parse API response, var remains nil

### ISSUE THREAD

**Issue by mrvantage** [ctreminiom/go-atlassian#260]
**v1.6.0**

**go-atlassian component**
- [X ] Jira Software Cloud
- [ ] Jira Agile Cloud
- [ ] Jira Service Management Cloud 
- [ ] Confluence Cloud
- [ ] Atlassian Admin Cloud

**Describe the bug** :bug:
When adding an attachment as described in the [documentation](https://docs.go-atlassian.io/jira-software-cloud/issues/attachments#add-attachment), the returned attachments is still a nil slice

**To Reproduce** :construction: 
When running the example code output is as follows:
```
2024/04/19 14:08:01 Using the path /absolute/path/to/sample.png
2024/04/19 14:08:03 Response HTTP Code 200
2024/04/19 14:08:03 HTTP Endpoint Used https://mydomain.atlassian.net/rest/api/3/issue/KP-2/attachments
2024/04/19 14:08:03 We've found 0 attachments
```

**Expected behavior** :white_check_mark: 
Expected output would be something like:
```
2024/04/19 14:08:01 Using the path /absolute/path/to/sample.png
2024/04/19 14:08:03 Response HTTP Code 200
2024/04/19 14:08:03 HTTP Endpoint Used https://mydomain.atlassian.net/rest/api/3/issue/KP-2/attachments
2024/04/19 14:07:38 We've found 1 attachments
2024/04/19 14:07:38 20522 sample.png
```

**Additional context**
When parsing the response the variable should be passed as reference

**Code snippet**
```go
	var attachments []*model.IssueAttachmentScheme
	response, err := i.c.Call(request, attachments)
	if err != nil {
		return nil, response, err
	}
```

I will create a pull request fixing this issue

**Comment by ctreminiom** [comment]
Hi @mrvantage, the PR has been merged, so I'm closing this issue..

thanks!
