### ISSUE TITLE
CLI for atlassian - Enhancement

### ISSUE THREAD

**Issue by christian1607** [ctreminiom/go-atlassian#30]
It would be great to develop a cli for atlassian (like github cli "gh"), maybe it could be another project which use many of this repo code

Benefits:
- This could help to some automation task for CI/CD
- A better and easy way to interact with atlassian

**Comment by ctreminiom** [comment]
Hi @christian1607, 

Thanks for your enhancement request, but unfortunately, the repository scope is the creation of the library, not the CLI, there are many CLI's that interact with Jira Cloud, for example:

- https://github.com/ankitpokhrel/jira-cli

Thanks for the request, but this is not a feature we consider for this library.
