### ISSUE TITLE
Users are unable to use `v2.0.0+` versions of the library

### ISSUE THREAD

**Issue by skovtunenko** [ctreminiom/go-atlassian#330]
**go-atlassian version**
`v2.0.0` - `v2.1.1`

**go-atlassian component**
- [X] Jira Software Cloud
- [X] Jira Agile Cloud
- [X] Jira Service Management Cloud 
- [X] Confluence Cloud
- [X] Atlassian Admin Cloud

**Describe the bug** :bug:

Users are unable to use `v2.0.0+` versions of the library.

The tagged version of the library `v2.0.0` - `v2.1.1` does not match the go module definition.

The Go module file should have `..../v2` at the end of the module name.

Quote from the documentation (https://go.dev/ref/mod#major-version-suffixes):
```
Starting with major version 2, module paths must have a major version suffix like /v2 that matches the major version. For example, if a module has the path example.com/mod at v1.0.0, it must have the path example.com/mod/v2 at version v2.0.0.
```

**To Reproduce** :construction: 

```
$ go get github.com/ctreminiom/go-atlassian
go: downloading github.com/ctreminiom/go-atlassian v1.6.1
go: added github.com/ctreminiom/go-atlassian v1.6.1

$ go get github.com/ctreminiom/go-atlassian@v2.1.1
go: github.com/ctreminiom/go-atlassian@v2.1.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/ctreminiom/go-atlassian/v2")
```

**Expected behavior** :white_check_mark: 

A version v2.1.1 should be downloaded

**Screenshots** :page_facing_up: 

None.

**Additional context**

None.

**Comment by ctreminiom** [comment]
Hi @skovtunenko, thanks for the report, my apologies.

can you please try it again?, it should download the version v2.1.2

**Comment by skovtunenko** [comment]
@ctreminiom, now it is working. I was able to download the latest lib.

I guess the Github pages need to be updated as well: https://docs.go-atlassian.io/#installation
